// This file is automatically generated. Do not edit it directly.
import { createClient, type Session, type AuthChangeEvent } from '@supabase/supabase-js';
import type { Database } from './types';

console.log("🔌 [SUPABASE] Initializing Supabase client");

// TODO: Replace with your own Supabase URL and publishable key
// NOTE: These are safe to expose in the frontend. Read more: https://supabase.com/docs/guides/api/api-keys
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMsg = "❌ [SUPABASE] Missing environment variables! Please create a .env file with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY";
  console.error(errorMsg);
  console.error("Current values:", { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY });
  // Show error in UI
  if (typeof window !== 'undefined') {
    document.body.innerHTML = `
      <div style="display: flex; align-items: center; justify-content: center; height: 100vh; font-family: system-ui; padding: 20px; text-align: center;">
        <div style="max-width: 600px;">
          <h1 style="color: #ef4444; margin-bottom: 16px;">⚠️ Configuration Error</h1>
          <p style="color: #64748b; margin-bottom: 8px;">Missing Supabase environment variables.</p>
          <p style="color: #64748b; margin-bottom: 16px;">Please create a <code style="background: #f1f5f9; padding: 2px 6px; border-radius: 4px;">.env</code> file in the project root with:</p>
          <pre style="background: #f1f5f9; padding: 16px; border-radius: 8px; text-align: left; overflow-x: auto;">
VITE_SUPABASE_URL=your_supabase_url
VITE_SUPABASE_ANON_KEY=your_supabase_anon_key</pre>
          <p style="color: #64748b; margin-top: 16px; font-size: 14px;">After creating the .env file, rebuild the app with: <code style="background: #f1f5f9; padding: 2px 6px; border-radius: 4px;">npm run build</code></p>
        </div>
      </div>
    `;
  }
  throw new Error(errorMsg);
}

console.log(`🔌 [SUPABASE] Using URL: ${SUPABASE_URL}`);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with debug logging and Realtime configuration
const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // Use localStorage for session persistence
    persistSession: true, // Enable session persistence across page reloads
    autoRefreshToken: true, // Automatically refresh tokens
    detectSessionInUrl: true, // Detect session in URL for OAuth redirects
    debug: true,
  },
  realtime: {
    params: {
      log_level: 'info', // Enable logging for Realtime connections
    },
  },
});

// Add logging for auth state changes for debugging
supabaseClient.auth.onAuthStateChange((event, session) => {
  console.log(`🔌 [SUPABASE_RAW_CLIENT] Auth event: ${event}, hasSession: ${!!session}`);
  // INITIAL_SESSION will now typically be null if persistSession is false
});

// Removed: explicit call to supabaseClient.auth.getSession() that logged any existing session.
// onAuthStateChange will fire with INITIAL_SESSION immediately.

// Create a wrapped client with logging for exports
export const supabase = {
  ...supabaseClient,
  // Add logging to auth methods
  auth: {
    ...supabaseClient.auth, // Spreading methods here can lead to `this` context issues for non-wrapped methods
    signInWithPassword: async (credentials: {email: string, password: string}) => {
      console.log(`🔌 [SUPABASE] Attempting sign in for: ${credentials.email}`);
      const result = await supabaseClient.auth.signInWithPassword(credentials);
      console.log('🔌 [SUPABASE] Sign in result:', { 
        success: !result.error,
        errorMessage: result.error?.message,
        hasUser: !!result.data.user,
        hasSession: !!result.data.session
      });
      return result;
    },
    signUp: async (credentials: {email: string, password: string}) => {
      console.log(`🔌 [SUPABASE] Attempting sign up for: ${credentials.email}`);
      const result = await supabaseClient.auth.signUp(credentials);
      console.log('🔌 [SUPABASE] Sign up result:', { 
        success: !result.error,
        errorMessage: result.error?.message,
        hasUser: !!result.data.user,
        hasSession: !!result.data.session
      });
      return result;
    },
    signOut: async () => {
      console.log('🔌 [SUPABASE] Signing out user');
      const result = await supabaseClient.auth.signOut();
      console.log('🔌 [SUPABASE] Sign out result:', { 
        success: !result.error,
        errorMessage: result.error?.message
      });
      return result;
    },
    getSession: async () => {
      console.log('🔌 [SUPABASE] Getting session');
      const result = await supabaseClient.auth.getSession();
      console.log('🔌 [SUPABASE] Get session result:', { 
        success: !result.error,
        hasSession: !!result.data.session
      });
      return result;
    },
    onAuthStateChange: (callback: (event: AuthChangeEvent, session: Session | null) => void) => {
      console.log('🔌 [SUPABASE WRAPPER] Registering onAuthStateChange callback');
      // Call the original onAuthStateChange method on the original supabaseClient.auth object
      // This ensures 'this' inside onAuthStateChange refers to supabaseClient.auth
      const result = supabaseClient.auth.onAuthStateChange(callback);
      console.log('🔌 [SUPABASE WRAPPER] onAuthStateChange subscription successful:', { hasSubscription: !!result.data.subscription });
      return result;
    },
  },
  // Add Storage API with logging
  storage: {
    from: (bucketName: string) => {
      console.log(`🔌 [SUPABASE] Storage operation on bucket: ${bucketName}`);
      return supabaseClient.storage.from(bucketName);
    }
  },
  // Forward other methods directly with type preservation
  from: <T extends keyof Database['public']['Tables']>(table: T) => {
    console.log(`🔌 [SUPABASE] Database query on table: ${table}`);
    return supabaseClient.from(table);
  },
  rpc: <T extends keyof Database['public']['Functions']>(fn: T, params?: Database['public']['Functions'][T]['Args']) => {
    console.log(`🔌 [SUPABASE] RPC call to function: ${fn}`);
    return supabaseClient.rpc(fn, params);
  },
  // Add Realtime capabilities with logging
  channel: (name: string, opts?: any) => {
    console.log(`🔌 [SUPABASE] Creating Realtime channel: ${name}`, opts);
    return supabaseClient.channel(name, opts);
  },
  realtime: {
    ...supabaseClient.realtime,
    setAuth: async (token?: string | null) => {
      console.log('🔌 [SUPABASE] Setting Realtime auth token');
      const result = await supabaseClient.realtime.setAuth(token);
      console.log('🔌 [SUPABASE] Realtime auth result: completed');
      return result;
    },
  },
  removeChannel: (channel: any) => {
    console.log('🔌 [SUPABASE] Removing Realtime channel');
    return supabaseClient.removeChannel(channel);
  }
};